
name: CI/CD

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Verify ECR access
        run: |
          aws ecr describe-repositories \
            --repository-names dev-frontend dev-backend \
            --region eu-west-1

      - name: Build frontend image
        run: |
          docker build \
            -t 322056173622.dkr.ecr.eu-west-1.amazonaws.com/dev-frontend:${{ github.sha }} \
            ./frontend

      - name: Build backend image
        run: |
          docker build \
            -t 322056173622.dkr.ecr.eu-west-1.amazonaws.com/dev-backend:${{ github.sha }} \
            ./backend

      - name: Scan frontend image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 322056173622.dkr.ecr.eu-west-1.amazonaws.com/dev-frontend:${{ github.sha }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Scan backend image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 322056173622.dkr.ecr.eu-west-1.amazonaws.com/dev-backend:${{ github.sha }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Push frontend image
        run: |
          docker push \
            322056173622.dkr.ecr.eu-west-1.amazonaws.com/dev-frontend:${{ github.sha }}

      - name: Push backend image
        run: |
          docker push \
            322056173622.dkr.ecr.eu-west-1.amazonaws.com/dev-backend:${{ github.sha }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/dev
        run: |
          terraform plan \
            -var="frontend_image=322056173622.dkr.ecr.eu-west-1.amazonaws.com/dev-frontend:${{ github.sha }}" \
            -var="backend_image=322056173622.dkr.ecr.eu-west-1.amazonaws.com/dev-backend:${{ github.sha }}"