name: Test AWS OIDC

on:
  push:
    branches: [dev]

permissions:
  id-token: write
  contents: read

jobs:
  oidc-test:
    runs-on: [ubuntu-latest]
   
    steps:

      - name: Debug OIDC
        uses: github/actions-oidc-debugger@main
        with:
          audience: sts.amazonaws.com.cn
        
       
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          audience: sts.amazonaws.com.cn
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_IM_ROLE }}
          

      - name: Verify AWS identity
        run: aws sts get-caller-identity
