name: Test AWS OIDC

on:
  push:
    branches: [dev]

permissions:
  id-token: write
  contents: read

jobs:
  oidc-test:
    runs-on: [ubuntu-latest]
   
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test STS with GitHub OIDC token
        env:
          AUDIENCE: sts.amazonaws.com
        run: |
          TOKEN_JSON=$(curl -s \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE")

          ID_TOKEN=$(echo "$TOKEN_JSON" | jq -r '.value')

          echo "Token obtained: $([ -n "$ID_TOKEN" ] && echo yes || echo no)"

          aws sts assume-role-with-web-identity \
            --role-arn arn:aws:iam::322056179999:role/GitHubActions-Terraform-Dev \
            --role-session-name GitHubOIDCTest \
            --web-identity-token "$ID_TOKEN" \
            --duration-seconds 900 \
            --region eu-west-1
       
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          audience: sts.amazonaws.com.cn
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_IM_ROLE }}
          

      - name: Verify AWS identity
        run: aws sts get-caller-identity
